server:
  port: "${PORT:8080}"
  forward-headers-strategy: framework

app:
  fontend-url: "${FRONTEND_URL:http://localhost:3000}"
  ngrok:
    fontend-url-public: "${FRONTEND_URL_PUBLIC:https://real-unlikely-mastiff.ngrok-free.app}"

spring:
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/MoodDiary}"
    username: "${SPRING_DATASOURCE_USERNAME:root}"
    password: "${SPRING_DATASOURCE_PASSWORD:root}"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${GOOGLE_CLIENT_ID}"
            client-secret: "${GOOGLE_CLIENT_SECRET}"
            scope: profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: "https://accounts.google.com/o/oauth2/v2/auth"
            token-uri: "https://oauth2.googleapis.com/token"
            user-info-uri: "https://www.googleapis.com/oauth2/v3/userinfo"
            user-name-attribute: "sub"

  data:
    redis:
      url: "${SPRING_REDIS_URL:redis://default:QjJaLtUgFTqzaMwTXjwGuRORiIllWCje@interchange.proxy.rlwy.net:34181}"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

cloudinary:
  cloud-name: "${CLOUDINARY_CLOUD_NAME:dmyrfnxfv}"
  api-key: "${CLOUDINARY_API_KEY:567893817722166}"
  api-secret: "${CLOUDINARY_API_SECRET:UXEZV0sENuJ1caxccS8P9H2dbCU}"


jwt:
  signerKey: "${JWT_SIGNER_KEY}"
  valid-duration: 86400
  refreshable-duration: 3000000
